version: "3.9"

services:
  codevideo_generator_backend:
    container_name: codevideo_generator_backend
    build:
      context: ../
      dockerfile: ./deployments/Dockerfile.local
    ports:
      - "$PORT:$PORT"
    networks:
      - codevideo_generator_backend_network

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./volumes/nginx:/etc/nginx
      - ./volumes/certbot/conf:/etc/letsencrypt
      - ./volumes/certbot/www:/var/www/certbot
    ports:
        - "80:80"
        - "443:443"
    depends_on:
        - "codevideo_generator_backend"
    networks:
      - codevideo_generator_backend_network
    restart: unless-stopped
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  
  certbot:
    container_name: certbot
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./volumes/certbot/conf:/etc/letsencrypt
      - ./volumes/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  codevideo_generator_backend_network:
    name: codevideo_generator_backend_network